AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC with public and private subnets'

Parameters:

      KeyName:
        Description: Select an existing EC2 KeyPair to enable SSH access to the Jenkins instance
        Type: AWS::EC2::KeyPair::KeyName
        ConstraintDescription: must be the name of an existing EC2 KeyPair.
    
      AvailabilityZone:
        Description: Select the Availability Zone
        Type: AWS::EC2::AvailabilityZone::Name

      ContainerPort:
        Type: Number
        Description: Enter the port on which the container listens (Eg:80)
        MinValue: 1
        MaxValue: 65535
        ConstraintDescription: must be between 1 and 65535.
        Default: 80

      ImageId:
        Type: String
        Description: Enter the Docker Image ID for the container (Eg:httpd:2.4)
        Default: httpd:2.4

      ClusterName:
        Type: String 
        Description: Enter the Name for Cluster. 
        Default: ECS

      VpcCIDR:
        Description: Please enter the IP range (CIDR notation) for this VPC(Eg:10.192.0.0/16)
        Type: String
        
      PublicSubnetCIDR:
        Description: Please enter the IP range (CIDR notation) for the public subnet in the Availability Zone(Eg:10.192.10.0/24)
        Type: String
        
      PrivateSubnetCIDR:
        Description: Please enter the IP range (CIDR notation) for the private subnet in the Availability Zone(Eg:10.192.12.0/24)
        Type: String

      TaskCpu:
        Description: Enter the number of cpu units used by the task (Eg:512) Refer more combinations on https://docs.aws.amazon.com/AmazonECS/latest/userguide/fargate-task-defs.html#fargate-tasks-size
        Type: Number

      TaskMemory:
        Description: Enter the amount of memory (in GiB) used by the task (Eg:2) Refer more combinations on https://docs.aws.amazon.com/AmazonECS/latest/userguide/fargate-task-defs.html#fargate-tasks-size
        Type: Number

      EmailId: 
        Type: String
        Description: Provide email to receive the alarm notifications for CPU Utilization of ECS Service (This product collects Email ID for the sole purpose of sending alarm notifications internally. It does not store or use for any other purpose.)
      
      AccessCIDR:
        Description: Please set CIDR to x.x.x.x/32 to allow one specific IP address access, 0.0.0.0/0 to allow all IP addresses access, or another CIDR range for application access
        Type: String

Mappings:
    RegionMap:
      us-east-1: 
        ami: ami-0d64bc69914c67143
      us-east-2:
        ami: ami-xxxxxxxxxxxxxxxxx
      us-west-1:
        ami: ami-xxxxxxxxxxxxxxxxx
      us-west-2:
        ami: ami-xxxxxxxxxxxxxxxxx
      ca-central-1:
        ami: ami-xxxxxxxxxxxxxxxxx
      eu-central-1:
        ami: ami-xxxxxxxxxxxxxxxxx
      eu-central-2:
        ami: ami-xxxxxxxxxxxxxxxxx
      eu-west-1:
        ami: ami-xxxxxxxxxxxxxxxxx
      eu-west-2:
        ami: ami-xxxxxxxxxxxxxxxxx
      eu-west-3:
        ami: ami-xxxxxxxxxxxxxxxxx
      eu-north-1: 
        ami: ami-xxxxxxxxxxxxxxxxx
      eu-south-1:
        ami: ami-xxxxxxxxxxxxxxxxx
      eu-south-2:
        ami: ami-xxxxxxxxxxxxxxxxx
      ap-northeast-1:
        ami: ami-xxxxxxxxxxxxxxxxx
      ap-northeast-2:
        ami: ami-xxxxxxxxxxxxxxxxx
      ap-northeast-3:
        ami: ami-xxxxxxxxxxxxxxxxx
      ap-southeast-1:
        ami: ami-xxxxxxxxxxxxxxxxx
      ap-southeast-2:
        ami: ami-xxxxxxxxxxxxxxxxx
      ap-southeast-3:
        ami: ami-xxxxxxxxxxxxxxxxx
      ap-southeast-4:
        ami: ami-xxxxxxxxxxxxxxxxx
      ap-south-1:
        ami: ami-xxxxxxxxxxxxxxxxx
      ap-south-2:
        ami: ami-xxxxxxxxxxxxxxxxx
      ap-east-1:
        ami: ami-xxxxxxxxxxxxxxxxx
      sa-east-1:
        ami: ami-xxxxxxxxxxxxxxxxx
      me-central-1:
        ami: ami-xxxxxxxxxxxxxxxxx
      me-south-1:
        ami: ami-xxxxxxxxxxxxxxxxx
      af-south-1:
        ami: ami-xxxxxxxxxxxxxxxxx

    JenkinsamiInstanceMap:
      us-east-1: 
        jenkinsami: ami-0f8c69f43bc5bc52b
      us-east-2:
        jenkinsami: ami-0da71b76be90b7f80
      us-west-1:
        jenkinsami: ami-0d83879b39980293f
      us-west-2:
        jenkinsami: ami-0e698c6ab5233cdbb
      ca-central-1:
        jenkinsami: ami-0f3d3ec5c58ec48d7
      eu-central-1:
        jenkinsami: ami-0e9b0be3ce8029296
      eu-central-2:
        jenkinsami: ami-0a2de5ac1d3e6c648
      eu-west-1:
        jenkinsami: ami-07c8327bfecb18ef4
      eu-west-2:
        jenkinsami: ami-08c91440c9cbe1e65
      eu-west-3:
        jenkinsami: ami-0436fdeea5a80d71f
      eu-north-1: 
        jenkinsami: ami-0a7cd6a8eee18aae8
      eu-south-1:
        jenkinsami: ami-046bb441ad11f44ef
      eu-south-2:
        jenkinsami: ami-08d0cfe166473a412
      ap-northeast-1:
        jenkinsami: ami-0125ab84d504d9e64
      ap-northeast-2:
        jenkinsami: ami-0c4e6702d8637bc3f
      ap-northeast-3:
        jenkinsami: ami-0a3f1d76f437f73b3
      ap-southeast-1:
        jenkinsami: ami-0756bd65518d5372a
      ap-southeast-2:
        jenkinsami: ami-068b0b3572bd3a6ae
      ap-southeast-3:
        jenkinsami: ami-06d4e7dacffdaa39c
      ap-southeast-4:
        jenkinsami: ami-0ccf1d08641160c8c
      ap-south-1:
        jenkinsami: ami-0e82e30d522c870b9
      ap-south-2:
        jenkinsami: ami-06c40323e38ade390
      ap-east-1:
        jenkinsami: ami-01649deffbf327a52
      sa-east-1:
        jenkinsami: ami-0f7af74c6b631fd26
      me-central-1:
        jenkinsami: ami-03a026889bb6a5205
      me-south-1:
        jenkinsami: ami-07f05d89ea6977820
      af-south-1:
        jenkinsami: ami-018536a82d2bbc1fb

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: "VPC Configuration"
        Parameters:
          - ClusterName
          - VpcCIDR
          - PublicSubnetCIDR
          - PrivateSubnetCIDR
          - AvailabilityZone
          - KeyName
          
      - Label:
          default: "Container Configuration"
        Parameters:
          - TaskCpu
          - TaskMemory
          - ContainerPort
          - ImageId
          - EmailId  
          - AccessCIDR  

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cloudformationecsfargatemarketplace.s3.amazonaws.com/vpc.yaml
      Parameters:
        VpcCIDR: !Ref VpcCIDR
        ClusterName: !Ref ClusterName
        ContainerPort: !Ref ContainerPort
        AccessCIDR: !Ref AccessCIDR
        PublicSubnetCIDR: !Ref PublicSubnetCIDR
        PrivateSubnetCIDR: !Ref PrivateSubnetCIDR
        AvailabilityZone: !Ref AvailabilityZone      

  EFS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cloudformationecsfargatemarketplace.s3.amazonaws.com/efsnodb.yaml
      Parameters:
        PerformanceMode: generalPurpose
        ThroughputMode: bursting
        EfsProvisionedThroughputInMibps: 0
        ClusterName: !Ref ClusterName
        VpcCIDR: !Ref VpcCIDR
        VPC: !GetAtt VPC.Outputs.VPC
        PublicSubnet: !GetAtt VPC.Outputs.PublicSubnet
        PrivateSubnet: !GetAtt VPC.Outputs.PrivateSubnet
        EFSSecurityGroup: !GetAtt VPC.Outputs.EFSSecurityGroup

  Cluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cloudformationecsfargatemarketplace.s3.amazonaws.com/ecsnodb.yaml
      Parameters:
        ClusterName: !Ref ClusterName
        ImageId: !Ref ImageId
        MinCapacity: 1
        MaxCapacity: 50
        TaskCpu: !Ref TaskCpu
        TaskMemory: !Ref TaskMemory
        ContainerPort: !Ref ContainerPort
        VPC: !GetAtt VPC.Outputs.VPC
        PublicSubnet: !GetAtt VPC.Outputs.PublicSubnet
        PrivateSubnet: !GetAtt VPC.Outputs.PrivateSubnet
        FileSystemId: !GetAtt EFS.Outputs.FileSystemId
        AccessPointId: !GetAtt EFS.Outputs.AccessPointId  
        ECSTaskRole: !GetAtt EFS.Outputs.TaskRole 
        ContainerSecurityGroup: !GetAtt VPC.Outputs.ContainerSecurityGroup

  Monitoring:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cloudformationecsfargatemarketplace.s3.amazonaws.com/monitoring.yaml
      Parameters:
        ClusterName: !Ref ClusterName
        ServiceName: !GetAtt Cluster.Outputs.service
        CPUAlarmThreshold: 75
        EmailId: !Ref EmailId


  Jenkins:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cloudformationecsfargatemarketplace.s3.amazonaws.com/jenkins.yaml
      Parameters:
        InstanceName: Jenkins
        InstanceType: t3.large
        VolumeSize: 40
        KeyName: !Ref KeyName
        VPC: !GetAtt VPC.Outputs.VPC
        PublicSubnet: !GetAtt VPC.Outputs.PublicSubnet
        Jenkinsami: !FindInMap [JenkinsamiInstanceMap, !Ref "AWS::Region", jenkinsami]
           
        
Outputs:
     Endpoint:
      Description: "Loadbalancer endpoint"
      Value: 
       !GetAtt Cluster.Outputs.Endpoint

     PublicIP:
      Description: "Public IP address of the created Jenkins EC2 instance"
      Value: 
       !GetAtt Jenkins.Outputs.PublicIP